// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExportSessions(arg1) {
  return window['go']['main']['App']['ExportSessions'](arg1);
}

export function FTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTPDownload'](arg1, arg2, arg3);
}

export function FTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['FTPMkdir'](arg1, arg2);
}

export function FTPRemove(arg1, arg2) {
  return window['go']['main']['App']['FTPRemove'](arg1, arg2);
}

export function FTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTPRename'](arg1, arg2, arg3);
}

export function FTPUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['FTPUpload'](arg1, arg2, arg3);
}

export function GenerateSSHKey(arg1, arg2) {
  return window['go']['main']['App']['GenerateSSHKey'](arg1, arg2);
}

export function GetConnectionState(arg1) {
  return window['go']['main']['App']['GetConnectionState'](arg1);
}

export function GetLatency(arg1) {
  return window['go']['main']['App']['GetLatency'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportMobaXterm(arg1) {
  return window['go']['main']['App']['ImportMobaXterm'](arg1);
}

export function ImportSSHConfig(arg1) {
  return window['go']['main']['App']['ImportSSHConfig'](arg1);
}

export function ImportSessions(arg1) {
  return window['go']['main']['App']['ImportSessions'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function LaunchProgram(arg1, arg2) {
  return window['go']['main']['App']['LaunchProgram'](arg1, arg2);
}

export function ListFTP(arg1, arg2) {
  return window['go']['main']['App']['ListFTP'](arg1, arg2);
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function ListSFTP(arg1, arg2) {
  return window['go']['main']['App']['ListSFTP'](arg1, arg2);
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function OpenSFTP(arg1) {
  return window['go']['main']['App']['OpenSFTP'](arg1);
}

export function PickDownloadDir() {
  return window['go']['main']['App']['PickDownloadDir']();
}

export function PickExecutable() {
  return window['go']['main']['App']['PickExecutable']();
}

export function RDPSendKeyDown(arg1, arg2, arg3) {
  return window['go']['main']['App']['RDPSendKeyDown'](arg1, arg2, arg3);
}

export function RDPSendKeyUp(arg1, arg2, arg3) {
  return window['go']['main']['App']['RDPSendKeyUp'](arg1, arg2, arg3);
}

export function RDPSendMouseDown(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RDPSendMouseDown'](arg1, arg2, arg3, arg4);
}

export function RDPSendMouseMove(arg1, arg2, arg3) {
  return window['go']['main']['App']['RDPSendMouseMove'](arg1, arg2, arg3);
}

export function RDPSendMouseUp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RDPSendMouseUp'](arg1, arg2, arg3, arg4);
}

export function RDPSendMouseWheel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RDPSendMouseWheel'](arg1, arg2, arg3, arg4);
}

export function RecordData(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordData'](arg1, arg2, arg3);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Resize'](arg1, arg2, arg3);
}

export function SFTPCreateFile(arg1, arg2) {
  return window['go']['main']['App']['SFTPCreateFile'](arg1, arg2);
}

export function SFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2, arg3);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPRemove(arg1, arg2) {
  return window['go']['main']['App']['SFTPRemove'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2, arg3);
}

export function SFTPUploadData(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUploadData'](arg1, arg2, arg3);
}

export function SaveFolder(arg1) {
  return window['go']['main']['App']['SaveFolder'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function Send(arg1, arg2) {
  return window['go']['main']['App']['Send'](arg1, arg2);
}

export function SendPassword(arg1, arg2) {
  return window['go']['main']['App']['SendPassword'](arg1, arg2);
}

export function SetMasterPassword(arg1) {
  return window['go']['main']['App']['SetMasterPassword'](arg1);
}

export function StartRecording(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2, arg3, arg4);
}

export function StopRecording(arg1) {
  return window['go']['main']['App']['StopRecording'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function VNCFrameSize(arg1) {
  return window['go']['main']['App']['VNCFrameSize'](arg1);
}

export function VNCRequestUpdate(arg1) {
  return window['go']['main']['App']['VNCRequestUpdate'](arg1);
}

export function VNCSendClipboard(arg1, arg2) {
  return window['go']['main']['App']['VNCSendClipboard'](arg1, arg2);
}

export function VNCSendKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['VNCSendKey'](arg1, arg2, arg3);
}

export function VNCSendPointer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VNCSendPointer'](arg1, arg2, arg3, arg4);
}
