// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {session} from '../models';
import {ftp} from '../models';
import {filetransfer} from '../models';

export function CheckForUpdate():Promise<config.ReleaseInfo>;

export function Connect(arg1:string,arg2:session.Session):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExportSessions(arg1:string):Promise<void>;

export function FTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FTPMkdir(arg1:string,arg2:string):Promise<void>;

export function FTPRemove(arg1:string,arg2:string):Promise<void>;

export function FTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GenerateSSHKey(arg1:string,arg2:string):Promise<string>;

export function GetConnectionState(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportMobaXterm(arg1:string):Promise<number>;

export function ImportSSHConfig(arg1:string):Promise<number>;

export function ImportSessions(arg1:string):Promise<number>;

export function InstallUpdate(arg1:string):Promise<void>;

export function IsLocked():Promise<boolean>;

export function ListFTP(arg1:string,arg2:string):Promise<Array<ftp.FileInfo>>;

export function ListFolders():Promise<Array<session.Folder>>;

export function ListSFTP(arg1:string,arg2:string):Promise<Array<filetransfer.FileInfo>>;

export function ListSerialPorts():Promise<Array<string>>;

export function ListSessions():Promise<Array<session.Session>>;

export function OpenSFTP(arg1:string):Promise<void>;

export function RDPSendKeyDown(arg1:string,arg2:number,arg3:string):Promise<void>;

export function RDPSendKeyUp(arg1:string,arg2:number,arg3:string):Promise<void>;

export function RDPSendMouseDown(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function RDPSendMouseMove(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RDPSendMouseUp(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function RDPSendMouseWheel(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function RecordData(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPRemove(arg1:string,arg2:string):Promise<void>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveFolder(arg1:session.Folder):Promise<void>;

export function SaveSession(arg1:session.Session):Promise<void>;

export function Send(arg1:string,arg2:string):Promise<void>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function StartLocalForward(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function StartRecording(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function StartRemoteForward(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function StartSOCKS5Proxy(arg1:string,arg2:number):Promise<void>;

export function StopRecording(arg1:string):Promise<void>;

export function Unlock(arg1:string):Promise<boolean>;

export function VNCFrameSize(arg1:string):Promise<number>;

export function VNCRequestUpdate(arg1:string):Promise<void>;

export function VNCSendKey(arg1:string,arg2:boolean,arg3:number):Promise<void>;

export function VNCSendPointer(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;
